stages:
  - build
  - run-app
  - test
  - debug

build-job:
  stage: build
  only:
    - master
  tags: 
    - cd
  script:
    - echo setting up env
    # - sudo apt-get install -y python-pip
    # - sudo pip install docker-compose
    - sudo docker system prune --volumes -f
    - sudo docker-compose -f docker-compose.yml build --no-cache --parallel

run-app-job:
  stage: run-app
  only:
    - master
  tags:
    - cd
  script:
    - sudo docker-compose -f docker-compose.yml up -d

test-mongo:
  stage: test
  only:
    - master
  tags: 
    - cd
  script:
    - sleep 60
    - sudo docker container inspect hha-app-mongo

test-server:
  stage: test
  only:
    - master
  tags: 
    - cd
  script:
    - sleep 60
    - sudo docker container inspect hha-app-server

test-client:
  stage: test
  only:
    - master
  tags: 
    - cd
  script:
    - sleep 60
    - sudo docker container inspect hha-app-client

check-errors-job:
  stage: debug
  only:
    - master
  tags: 
    - cd
  script:
    - sudo docker-compose logs
  when: on_failure

# deploy-job:
#   stage: deploy
#   only:
#     - master
#   tags: 
#     - cd
#   script:
#     - sudo docker-compose -f docker-compose.yml up -d
#     - echo complete