stages:
  - build
  - start
  - test
  - log

build-job:
  stage: build
  only:
    - master
  tags: 
    - cd
  script:
    - echo setting up env
    # - sudo apt-get install -y python-pip
    # - sudo pip install docker-compose
    - sudo docker system prune --volumes -f
    - sudo docker-compose -f docker-compose.yml build --no-cache --parallel
    - sudo docker system prune --volumes -f

build-cache:
  stage: build
  except:
    - master
  tags: 
    - cd
  script:
    - sudo docker system prune --volumes -f
    - sudo docker-compose -f docker-compose.yml build --parallel
    - sudo docker system prune --volumes -f

start-app:
  stage: start
  tags:
    - cd
  script:
    - sudo docker-compose -f docker-compose.yml up -d
    - sleep 60

test-mongo:
  stage: test
  tags: 
    - cd
  script:
    - sudo docker ps | grep hha-app-mongo

test-server:
  stage: test
  tags: 
    - cd
  script:
    - sudo docker ps | grep hha-app-server

test-client:
  stage: test
  tags: 
    - cd
  script:
    - sudo docker ps | grep hha-app-client

log-mongo:
  stage: log
  needs: ["test-mongo"]
  tags: 
    - cd
  script:
    - sudo docker-compose logs mongodb
  when: on_failure

log-server:
  stage: log
  needs: ["test-server"]
  tags: 
    - cd
  script:
    - sudo docker-compose logs server
  when: on_failure

log-client:
  stage: log
  needs: ["test-client"]
  tags: 
    - cd
  script:
    - sudo docker-compose logs client
  when: on_failure

# deploy-job:
#   stage: deploy
#   only:
#     - master
#   tags: 
#     - cd
#   script:
#     - sudo docker-compose -f docker-compose.yml up -d
#     - echo complete