stages:
  - build
  - start
  - test

build-job:
  stage: build
  only:
    - master
  tags: 
    - cd
  script:
    - echo setting up env
    # - sudo apt-get install -y python-pip
    # - sudo pip install docker-compose
    - sudo docker-compose down
    - sudo docker system prune --volumes -f
    - sudo docker-compose -f docker-compose.yml build --no-cache --parallel
    - sudo docker system prune --volumes -f

build-cache:
  stage: build
  except:
    - master
  tags: 
    - cd
  script:
    - sudo docker-compose down
    - sudo docker system prune --volumes -f
    - sudo docker-compose -f docker-compose.yml build --parallel
    - sudo docker system prune --volumes -f

start-app:
  stage: start
  tags:
    - cd
  script:
    - CI=false sudo docker-compose -f docker-compose.yml up -d
    # - sudo docker image prune -af
    - sleep 60

test-mongo:
  stage: test
  tags: 
    - cd
  script:
    - sudo docker-compose logs mongodb
    - sudo docker ps | grep hha-app-mongo

test-server:
  stage: test
  tags: 
    - cd
  script:
    - sudo docker-compose logs server
    - sudo docker ps | grep hha-app-server

test-client:
  stage: test
  tags: 
    - cd
  script:
    - sudo docker-compose logs client
    - sudo docker ps | grep hha-app-client
    - sudo docker logs hha-app-client | ( ! grep "Failed to compile")

# deploy-job:
#   stage: deploy
#   only:
#     - master
#   tags: 
#     - cd
#   script:
#     - sudo docker-compose -f docker-compose.yml up -d
#     - echo complete