deploy-to-linux-vm:
  stage: deploy
  only:
    - master
  tags: 
    - cd
  script:
    - echo setting up env
    # - sudo apt-get install -y python-pip
    # - sudo pip install docker-compose
    - sudo docker system prune --volumes -f
    - sudo docker-compose -f docker-compose.yml build --no-cache --parallel
    - sudo docker-compose -f docker-compose.yml up
    - echo complete
# test
