version: '3.7'

services:
  server:
    network_mode: host
    build:
      context: ./server
      dockerfile: Dockerfile
    image: myapp-server
    container_name: myapp-server
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
  mongodb:
    network_mode: host
    container_name: myapp-mongodb
    image: mongo
    volumes:
      - data-volume:/data/db
  client:
    network_mode: host
    build:
      context: ./client
      dockerfile: Dockerfile
    image: myapp-client
    container_name: myapp-client
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    stdin_open: true # docker run -i
    tty: true        # docker run -t

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
